# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Noah\Documents\College\GuiProjects\Compressor_1\compressorGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1547, 824)
        Dialog.setStyleSheet(_fromUtf8("background:rgb(70, 80, 88)"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 20, 761, 471))
        self.frame.setStyleSheet(_fromUtf8("background: rgb(52, 73, 94)"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.labelCompressor = QtGui.QLabel(self.frame)
        self.labelCompressor.setGeometry(QtCore.QRect(10, 10, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelCompressor.setFont(font)
        self.labelCompressor.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompressor.setScaledContents(True)
        self.labelCompressor.setObjectName(_fromUtf8("labelCompressor"))
        self.dataCompTempIn = QtGui.QLCDNumber(self.frame)
        self.dataCompTempIn.setGeometry(QtCore.QRect(260, 140, 351, 61))
        self.dataCompTempIn.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataCompTempIn.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataCompTempIn.setFrameShadow(QtGui.QFrame.Plain)
        self.dataCompTempIn.setLineWidth(10)
        self.dataCompTempIn.setMidLineWidth(4)
        self.dataCompTempIn.setSmallDecimalPoint(False)
        self.dataCompTempIn.setNumDigits(11)
        self.dataCompTempIn.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataCompTempIn.setProperty("value", 0.0)
        self.dataCompTempIn.setObjectName(_fromUtf8("dataCompTempIn"))
        self.labelCompWaterTempIn = QtGui.QLabel(self.frame)
        self.labelCompWaterTempIn.setGeometry(QtCore.QRect(50, 140, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelCompWaterTempIn.setFont(font)
        self.labelCompWaterTempIn.setAcceptDrops(False)
        self.labelCompWaterTempIn.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompWaterTempIn.setFrameShadow(QtGui.QFrame.Plain)
        self.labelCompWaterTempIn.setWordWrap(True)
        self.labelCompWaterTempIn.setObjectName(_fromUtf8("labelCompWaterTempIn"))
        self.labelCompWaterTempOut = QtGui.QLabel(self.frame)
        self.labelCompWaterTempOut.setGeometry(QtCore.QRect(30, 210, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelCompWaterTempOut.setFont(font)
        self.labelCompWaterTempOut.setAcceptDrops(False)
        self.labelCompWaterTempOut.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompWaterTempOut.setFrameShadow(QtGui.QFrame.Plain)
        self.labelCompWaterTempOut.setWordWrap(True)
        self.labelCompWaterTempOut.setObjectName(_fromUtf8("labelCompWaterTempOut"))
        self.dataCompTempOut = QtGui.QLCDNumber(self.frame)
        self.dataCompTempOut.setGeometry(QtCore.QRect(260, 210, 351, 61))
        self.dataCompTempOut.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataCompTempOut.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataCompTempOut.setFrameShadow(QtGui.QFrame.Plain)
        self.dataCompTempOut.setLineWidth(10)
        self.dataCompTempOut.setMidLineWidth(4)
        self.dataCompTempOut.setSmallDecimalPoint(False)
        self.dataCompTempOut.setNumDigits(11)
        self.dataCompTempOut.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataCompTempOut.setObjectName(_fromUtf8("dataCompTempOut"))
        self.labelCompWaterFlowRate = QtGui.QLabel(self.frame)
        self.labelCompWaterFlowRate.setGeometry(QtCore.QRect(110, 370, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelCompWaterFlowRate.setFont(font)
        self.labelCompWaterFlowRate.setAcceptDrops(False)
        self.labelCompWaterFlowRate.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompWaterFlowRate.setFrameShadow(QtGui.QFrame.Plain)
        self.labelCompWaterFlowRate.setWordWrap(True)
        self.labelCompWaterFlowRate.setObjectName(_fromUtf8("labelCompWaterFlowRate"))
        self.dataCompFlowRate = QtGui.QLCDNumber(self.frame)
        self.dataCompFlowRate.setGeometry(QtCore.QRect(260, 370, 351, 61))
        self.dataCompFlowRate.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataCompFlowRate.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataCompFlowRate.setFrameShadow(QtGui.QFrame.Plain)
        self.dataCompFlowRate.setLineWidth(10)
        self.dataCompFlowRate.setMidLineWidth(4)
        self.dataCompFlowRate.setSmallDecimalPoint(False)
        self.dataCompFlowRate.setNumDigits(11)
        self.dataCompFlowRate.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataCompFlowRate.setObjectName(_fromUtf8("dataCompFlowRate"))
        self.labelCompWater = QtGui.QLabel(self.frame)
        self.labelCompWater.setGeometry(QtCore.QRect(10, 80, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelCompWater.setFont(font)
        self.labelCompWater.setAcceptDrops(False)
        self.labelCompWater.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompWater.setFrameShadow(QtGui.QFrame.Plain)
        self.labelCompWater.setWordWrap(True)
        self.labelCompWater.setObjectName(_fromUtf8("labelCompWater"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(10, 70, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.dataCompState = QtGui.QLabel(self.frame)
        self.dataCompState.setGeometry(QtCore.QRect(260, 10, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dataCompState.setFont(font)
        self.dataCompState.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.dataCompState.setObjectName(_fromUtf8("dataCompState"))
        self.inputCompOnOff = QtGui.QPushButton(self.frame)
        self.inputCompOnOff.setGeometry(QtCore.QRect(420, 10, 191, 61))
        self.inputCompOnOff.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199); background: rgb(52, 73, 94)\n"
""))
        self.inputCompOnOff.setObjectName(_fromUtf8("inputCompOnOff"))
        self.labelCompUnitC_2 = QtGui.QLabel(self.frame)
        self.labelCompUnitC_2.setGeometry(QtCore.QRect(620, 140, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelCompUnitC_2.setFont(font)
        self.labelCompUnitC_2.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompUnitC_2.setObjectName(_fromUtf8("labelCompUnitC_2"))
        self.labelCompUnitC_3 = QtGui.QLabel(self.frame)
        self.labelCompUnitC_3.setGeometry(QtCore.QRect(620, 210, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelCompUnitC_3.setFont(font)
        self.labelCompUnitC_3.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompUnitC_3.setObjectName(_fromUtf8("labelCompUnitC_3"))
        self.labelCompUnitFlowRate_1 = QtGui.QLabel(self.frame)
        self.labelCompUnitFlowRate_1.setGeometry(QtCore.QRect(620, 370, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelCompUnitFlowRate_1.setFont(font)
        self.labelCompUnitFlowRate_1.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompUnitFlowRate_1.setObjectName(_fromUtf8("labelCompUnitFlowRate_1"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(10, 280, 741, 20))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.labelCompExtTemp = QtGui.QLabel(self.frame)
        self.labelCompExtTemp.setGeometry(QtCore.QRect(20, 300, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.labelCompExtTemp.setFont(font)
        self.labelCompExtTemp.setAcceptDrops(False)
        self.labelCompExtTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompExtTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.labelCompExtTemp.setWordWrap(True)
        self.labelCompExtTemp.setObjectName(_fromUtf8("labelCompExtTemp"))
        self.dataCompExtTemp = QtGui.QLCDNumber(self.frame)
        self.dataCompExtTemp.setGeometry(QtCore.QRect(260, 300, 351, 61))
        self.dataCompExtTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataCompExtTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataCompExtTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataCompExtTemp.setLineWidth(10)
        self.dataCompExtTemp.setMidLineWidth(4)
        self.dataCompExtTemp.setSmallDecimalPoint(False)
        self.dataCompExtTemp.setNumDigits(11)
        self.dataCompExtTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataCompExtTemp.setObjectName(_fromUtf8("dataCompExtTemp"))
        self.labelCompUnitExtTemp_1 = QtGui.QLabel(self.frame)
        self.labelCompUnitExtTemp_1.setGeometry(QtCore.QRect(620, 300, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelCompUnitExtTemp_1.setFont(font)
        self.labelCompUnitExtTemp_1.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelCompUnitExtTemp_1.setObjectName(_fromUtf8("labelCompUnitExtTemp_1"))
        self.datatime = QtGui.QLabel(Dialog)
        self.datatime.setGeometry(QtCore.QRect(800, 660, 261, 23))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.datatime.setFont(font)
        self.datatime.setStyleSheet(_fromUtf8("border-color: rgb(200,0,0);\n"
"color:rgb(189, 195, 199);\n"
"background-color: rgb(52, 73, 94);\n"
""))
        self.datatime.setFrameShape(QtGui.QFrame.NoFrame)
        self.datatime.setFrameShadow(QtGui.QFrame.Plain)
        self.datatime.setLineWidth(0)
        self.datatime.setAlignment(QtCore.Qt.AlignCenter)
        self.datatime.setObjectName(_fromUtf8("datatime"))
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 500, 761, 311))
        self.frame_2.setStyleSheet(_fromUtf8("background: rgb(52, 73, 94)"))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.labelPresPresOVC = QtGui.QLabel(self.frame_2)
        self.labelPresPresOVC.setGeometry(QtCore.QRect(70, 90, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPresPresOVC.setFont(font)
        self.labelPresPresOVC.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresPresOVC.setObjectName(_fromUtf8("labelPresPresOVC"))
        self.dataPresPresOVC = QtGui.QLCDNumber(self.frame_2)
        self.dataPresPresOVC.setGeometry(QtCore.QRect(260, 90, 351, 61))
        self.dataPresPresOVC.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataPresPresOVC.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataPresPresOVC.setFrameShadow(QtGui.QFrame.Plain)
        self.dataPresPresOVC.setLineWidth(10)
        self.dataPresPresOVC.setMidLineWidth(4)
        self.dataPresPresOVC.setSmallDecimalPoint(False)
        self.dataPresPresOVC.setNumDigits(11)
        self.dataPresPresOVC.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataPresPresOVC.setObjectName(_fromUtf8("dataPresPresOVC"))
        self.labelPresUnits_1 = QtGui.QLabel(self.frame_2)
        self.labelPresUnits_1.setGeometry(QtCore.QRect(620, 90, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPresUnits_1.setFont(font)
        self.labelPresUnits_1.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresUnits_1.setObjectName(_fromUtf8("labelPresUnits_1"))
        self.labelFridgePres = QtGui.QLabel(self.frame_2)
        self.labelFridgePres.setGeometry(QtCore.QRect(10, 10, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelFridgePres.setFont(font)
        self.labelFridgePres.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelFridgePres.setScaledContents(True)
        self.labelFridgePres.setObjectName(_fromUtf8("labelFridgePres"))
        self.labelPresPresIVC = QtGui.QLabel(self.frame_2)
        self.labelPresPresIVC.setGeometry(QtCore.QRect(70, 160, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPresPresIVC.setFont(font)
        self.labelPresPresIVC.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresPresIVC.setObjectName(_fromUtf8("labelPresPresIVC"))
        self.labelPresUnits_2 = QtGui.QLabel(self.frame_2)
        self.labelPresUnits_2.setGeometry(QtCore.QRect(620, 160, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPresUnits_2.setFont(font)
        self.labelPresUnits_2.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresUnits_2.setObjectName(_fromUtf8("labelPresUnits_2"))
        self.dataPresPresIVC = QtGui.QLCDNumber(self.frame_2)
        self.dataPresPresIVC.setGeometry(QtCore.QRect(260, 160, 351, 61))
        self.dataPresPresIVC.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataPresPresIVC.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataPresPresIVC.setFrameShadow(QtGui.QFrame.Plain)
        self.dataPresPresIVC.setLineWidth(10)
        self.dataPresPresIVC.setMidLineWidth(4)
        self.dataPresPresIVC.setSmallDecimalPoint(False)
        self.dataPresPresIVC.setNumDigits(11)
        self.dataPresPresIVC.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataPresPresIVC.setObjectName(_fromUtf8("dataPresPresIVC"))
        self.labelPresStillPres = QtGui.QLabel(self.frame_2)
        self.labelPresStillPres.setGeometry(QtCore.QRect(70, 230, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPresStillPres.setFont(font)
        self.labelPresStillPres.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresStillPres.setObjectName(_fromUtf8("labelPresStillPres"))
        self.dataPresStillPress = QtGui.QLCDNumber(self.frame_2)
        self.dataPresStillPress.setGeometry(QtCore.QRect(260, 230, 351, 61))
        self.dataPresStillPress.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataPresStillPress.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataPresStillPress.setFrameShadow(QtGui.QFrame.Plain)
        self.dataPresStillPress.setLineWidth(10)
        self.dataPresStillPress.setMidLineWidth(4)
        self.dataPresStillPress.setSmallDecimalPoint(False)
        self.dataPresStillPress.setNumDigits(11)
        self.dataPresStillPress.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataPresStillPress.setObjectName(_fromUtf8("dataPresStillPress"))
        self.labelPresUnits_3 = QtGui.QLabel(self.frame_2)
        self.labelPresUnits_3.setGeometry(QtCore.QRect(620, 230, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPresUnits_3.setFont(font)
        self.labelPresUnits_3.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelPresUnits_3.setObjectName(_fromUtf8("labelPresUnits_3"))
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(10, 70, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame_3 = QtGui.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(780, 20, 751, 541))
        self.frame_3.setStyleSheet(_fromUtf8("background: rgb(52, 73, 94)"))
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.labelTempStillTemp = QtGui.QLabel(self.frame_3)
        self.labelTempStillTemp.setGeometry(QtCore.QRect(250, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTempStillTemp.setFont(font)
        self.labelTempStillTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempStillTemp.setObjectName(_fromUtf8("labelTempStillTemp"))
        self.dataTempStillTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTempStillTemp.setGeometry(QtCore.QRect(320, 90, 351, 61))
        self.dataTempStillTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTempStillTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTempStillTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTempStillTemp.setLineWidth(10)
        self.dataTempStillTemp.setMidLineWidth(4)
        self.dataTempStillTemp.setSmallDecimalPoint(False)
        self.dataTempStillTemp.setNumDigits(11)
        self.dataTempStillTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTempStillTemp.setObjectName(_fromUtf8("dataTempStillTemp"))
        self.labelTempUnitC_1 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_1.setGeometry(QtCore.QRect(680, 90, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_1.setFont(font)
        self.labelTempUnitC_1.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_1.setObjectName(_fromUtf8("labelTempUnitC_1"))
        self.labelFridgeTemp = QtGui.QLabel(self.frame_3)
        self.labelFridgeTemp.setGeometry(QtCore.QRect(10, 10, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelFridgeTemp.setFont(font)
        self.labelFridgeTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelFridgeTemp.setScaledContents(True)
        self.labelFridgeTemp.setObjectName(_fromUtf8("labelFridgeTemp"))
        self.labelTempExTemp = QtGui.QLabel(self.frame_3)
        self.labelTempExTemp.setGeometry(QtCore.QRect(180, 160, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTempExTemp.setFont(font)
        self.labelTempExTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempExTemp.setObjectName(_fromUtf8("labelTempExTemp"))
        self.dataTempExTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTempExTemp.setGeometry(QtCore.QRect(320, 160, 351, 61))
        self.dataTempExTemp.setAutoFillBackground(False)
        self.dataTempExTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTempExTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTempExTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTempExTemp.setLineWidth(10)
        self.dataTempExTemp.setMidLineWidth(4)
        self.dataTempExTemp.setSmallDecimalPoint(False)
        self.dataTempExTemp.setNumDigits(11)
        self.dataTempExTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTempExTemp.setObjectName(_fromUtf8("dataTempExTemp"))
        self.labelTempMixTTTemp = QtGui.QLabel(self.frame_3)
        self.labelTempMixTTTemp.setGeometry(QtCore.QRect(190, 230, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTempMixTTTemp.setFont(font)
        self.labelTempMixTTTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempMixTTTemp.setObjectName(_fromUtf8("labelTempMixTTTemp"))
        self.dataTempMixTTTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTempMixTTTemp.setGeometry(QtCore.QRect(320, 230, 351, 61))
        self.dataTempMixTTTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTempMixTTTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTempMixTTTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTempMixTTTemp.setLineWidth(10)
        self.dataTempMixTTTemp.setMidLineWidth(4)
        self.dataTempMixTTTemp.setSmallDecimalPoint(False)
        self.dataTempMixTTTemp.setNumDigits(11)
        self.dataTempMixTTTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTempMixTTTemp.setObjectName(_fromUtf8("dataTempMixTTTemp"))
        self.line_7 = QtGui.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(10, 70, 731, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_7.setFont(font)
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setLineWidth(1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.labelTempUnitC_3 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_3.setGeometry(QtCore.QRect(680, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_3.setFont(font)
        self.labelTempUnitC_3.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_3.setObjectName(_fromUtf8("labelTempUnitC_3"))
        self.labelTempUnitC_4 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_4.setGeometry(QtCore.QRect(680, 230, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_4.setFont(font)
        self.labelTempUnitC_4.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_4.setObjectName(_fromUtf8("labelTempUnitC_4"))
        self.line_8 = QtGui.QFrame(self.frame_3)
        self.line_8.setGeometry(QtCore.QRect(10, 300, 731, 20))
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.labelTempMixPTTemp = QtGui.QLabel(self.frame_3)
        self.labelTempMixPTTemp.setGeometry(QtCore.QRect(130, 320, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTempMixPTTemp.setFont(font)
        self.labelTempMixPTTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempMixPTTemp.setObjectName(_fromUtf8("labelTempMixPTTemp"))
        self.dataTempMixPTTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTempMixPTTemp.setGeometry(QtCore.QRect(320, 320, 351, 61))
        self.dataTempMixPTTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTempMixPTTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTempMixPTTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTempMixPTTemp.setLineWidth(10)
        self.dataTempMixPTTemp.setMidLineWidth(4)
        self.dataTempMixPTTemp.setSmallDecimalPoint(False)
        self.dataTempMixPTTemp.setNumDigits(11)
        self.dataTempMixPTTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTempMixPTTemp.setObjectName(_fromUtf8("dataTempMixPTTemp"))
        self.labelTempUnitC_5 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_5.setGeometry(QtCore.QRect(680, 320, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_5.setFont(font)
        self.labelTempUnitC_5.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_5.setObjectName(_fromUtf8("labelTempUnitC_5"))
        self.dataTemp50KTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTemp50KTemp.setGeometry(QtCore.QRect(320, 390, 351, 61))
        self.dataTemp50KTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTemp50KTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTemp50KTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTemp50KTemp.setLineWidth(10)
        self.dataTemp50KTemp.setMidLineWidth(4)
        self.dataTemp50KTemp.setSmallDecimalPoint(False)
        self.dataTemp50KTemp.setNumDigits(11)
        self.dataTemp50KTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTemp50KTemp.setObjectName(_fromUtf8("dataTemp50KTemp"))
        self.labelTempUnitC_6 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_6.setGeometry(QtCore.QRect(680, 390, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_6.setFont(font)
        self.labelTempUnitC_6.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_6.setObjectName(_fromUtf8("labelTempUnitC_6"))
        self.labelTemp50K = QtGui.QLabel(self.frame_3)
        self.labelTemp50K.setGeometry(QtCore.QRect(250, 390, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp50K.setFont(font)
        self.labelTemp50K.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTemp50K.setObjectName(_fromUtf8("labelTemp50K"))
        self.labelTempUnitC_7 = QtGui.QLabel(self.frame_3)
        self.labelTempUnitC_7.setGeometry(QtCore.QRect(680, 460, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTempUnitC_7.setFont(font)
        self.labelTempUnitC_7.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTempUnitC_7.setObjectName(_fromUtf8("labelTempUnitC_7"))
        self.labelTemp3K = QtGui.QLabel(self.frame_3)
        self.labelTemp3K.setGeometry(QtCore.QRect(269, 460, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTemp3K.setFont(font)
        self.labelTemp3K.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);"))
        self.labelTemp3K.setObjectName(_fromUtf8("labelTemp3K"))
        self.dataTemp3KTemp = QtGui.QLCDNumber(self.frame_3)
        self.dataTemp3KTemp.setGeometry(QtCore.QRect(320, 460, 351, 61))
        self.dataTemp3KTemp.setStyleSheet(_fromUtf8("color:rgb(189, 195, 199);\n"
"background: rgb(52, 73, 94)\n"
""))
        self.dataTemp3KTemp.setFrameShape(QtGui.QFrame.WinPanel)
        self.dataTemp3KTemp.setFrameShadow(QtGui.QFrame.Plain)
        self.dataTemp3KTemp.setLineWidth(10)
        self.dataTemp3KTemp.setMidLineWidth(4)
        self.dataTemp3KTemp.setSmallDecimalPoint(False)
        self.dataTemp3KTemp.setNumDigits(11)
        self.dataTemp3KTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dataTemp3KTemp.setObjectName(_fromUtf8("dataTemp3KTemp"))
        self.frame_4 = QtGui.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(780, 640, 301, 61))
        self.frame_4.setStyleSheet(_fromUtf8("background: rgb(52, 73, 94)"))
        self.frame_4.setFrameShape(QtGui.QFrame.Panel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame_5 = QtGui.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(780, 570, 751, 61))
        self.frame_5.setStyleSheet(_fromUtf8("background: rgb(52, 73, 94)"))
        self.frame_5.setFrameShape(QtGui.QFrame.Panel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.dataStatus = QtGui.QLabel(self.frame_5)
        self.dataStatus.setGeometry(QtCore.QRect(20, 20, 711, 23))
        self.dataStatus.setStyleSheet(_fromUtf8("border-color: rgb(200,0,0);\n"
"color:rgb(189, 195, 199);\n"
"background-color: rgb(52, 73, 94);\n"
""))
        self.dataStatus.setFrameShape(QtGui.QFrame.NoFrame)
        self.dataStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.dataStatus.setObjectName(_fromUtf8("dataStatus"))
        self.frame_5.raise_()
        self.frame_4.raise_()
        self.frame.raise_()
        self.datatime.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.labelCompressor.setText(_translate("Dialog", "Compressor:", None))
        self.labelCompWaterTempIn.setText(_translate("Dialog", "Temperature In", None))
        self.labelCompWaterTempOut.setText(_translate("Dialog", "Temperature Out", None))
        self.labelCompWaterFlowRate.setText(_translate("Dialog", "Flow Rate", None))
        self.labelCompWater.setText(_translate("Dialog", "Water", None))
        self.dataCompState.setText(_translate("Dialog", "Running", None))
        self.inputCompOnOff.setText(_translate("Dialog", "Turn On/off", None))
        self.labelCompUnitC_2.setText(_translate("Dialog", "C", None))
        self.labelCompUnitC_3.setText(_translate("Dialog", "C", None))
        self.labelCompUnitFlowRate_1.setText(_translate("Dialog", "Gal/min", None))
        self.labelCompExtTemp.setText(_translate("Dialog", "Ext. Temperature", None))
        self.labelCompUnitExtTemp_1.setText(_translate("Dialog", "C", None))
        self.datatime.setText(_translate("Dialog", "Time", None))
        self.labelPresPresOVC.setText(_translate("Dialog", "Pressure OVC", None))
        self.labelPresUnits_1.setText(_translate("Dialog", "bar", None))
        self.labelFridgePres.setText(_translate("Dialog", "Fridge Pressure", None))
        self.labelPresPresIVC.setText(_translate("Dialog", "Pressure IVC", None))
        self.labelPresUnits_2.setText(_translate("Dialog", "bar", None))
        self.labelPresStillPres.setText(_translate("Dialog", "Still Pressure", None))
        self.labelPresUnits_3.setText(_translate("Dialog", "bar", None))
        self.labelTempStillTemp.setText(_translate("Dialog", "Still", None))
        self.labelTempUnitC_1.setText(_translate("Dialog", "C", None))
        self.labelFridgeTemp.setText(_translate("Dialog", "Fridge Temperature", None))
        self.labelTempExTemp.setText(_translate("Dialog", "Exchange", None))
        self.labelTempMixTTTemp.setText(_translate("Dialog", "Mix (TT)", None))
        self.labelTempUnitC_3.setText(_translate("Dialog", "C", None))
        self.labelTempUnitC_4.setText(_translate("Dialog", "C", None))
        self.labelTempMixPTTemp.setText(_translate("Dialog", "Mix (PT-1000)", None))
        self.labelTempUnitC_5.setText(_translate("Dialog", "C", None))
        self.labelTempUnitC_6.setText(_translate("Dialog", "C", None))
        self.labelTemp50K.setText(_translate("Dialog", "50K", None))
        self.labelTempUnitC_7.setText(_translate("Dialog", "C", None))
        self.labelTemp3K.setText(_translate("Dialog", "3K", None))
        self.dataStatus.setText(_translate("Dialog", "Status", None))

